spring.application.name=jobpilot-ai

spring.datasource.url=jdbc:mysql://localhost:3306/jobpilot
spring.datasource.username=root
spring.datasource.password=H@ri2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

